### ISSUE TITLE
http://yaml.org/ypaste is down

### ISSUE THREAD

**Issue by Byron** [yaml/yaml-org-site#7]
See subject. This is how it looks like to me.

![screen shot 2015-06-01 at 17 25 17 1](https://cloud.githubusercontent.com/assets/63622/7916299/4d885166-0883-11e5-997f-1b32f5094d17.png)

The link is shown on yaml.org.

**Comment by ajlanghorn** [comment]
Yep - still 404ing for me.

**Comment by j13k** [comment]
+1

**Comment by wernight** [comment]
Wow 1 year still down

**Comment by orenbenkiki** [comment]
It is up under a new URL, ben-kiki.org/ypaste - Ingy needs to fix the link
to it.

**Comment by yaml-org** [comment]
Fixed.
